// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/addresses": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Address"
                ],
                "summary": "住所一覧を取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zip Code",
                        "name": "zip_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Prefecture",
                        "name": "prefecture",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "City",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Address Line1",
                        "name": "address_line1",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Address Line2",
                        "name": "address_line2",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Latitude",
                        "name": "latitude",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Longitude",
                        "name": "longitude",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation_address.AddressDetailResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Address"
                ],
                "summary": "住所を作成する",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_address.CreateAddressResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/addresses/{address_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Address"
                ],
                "summary": "単一の住所を取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Address ID",
                        "name": "address_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_address.AddressDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/areas/{area_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Area"
                ],
                "summary": "単一のエリアを取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Area ID",
                        "name": "area_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_area.AreaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "サインイン用エンドポイント",
                "parameters": [
                    {
                        "description": "Sign In Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation_auth.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_auth.SignInResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "サインアップ用エンドポイント",
                "parameters": [
                    {
                        "description": "Sign Up Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation_auth.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_auth.SignUpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/departments/{department_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "単一の部署を取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department ID",
                        "name": "department_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_department.DepartmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/facilities/{facility_id}/areas": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Area"
                ],
                "summary": "施設IDに紐づくエリアを取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Facility ID",
                        "name": "facility_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_area.AreaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Area"
                ],
                "summary": "施設に紐づくエリアを作成する",
                "parameters": [
                    {
                        "description": "Create Area Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_area.CreateAreaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_area.AreaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/facilities/{facility_id}/departments": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "施設IDに紐づく部署を取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Facility ID",
                        "name": "facility_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_department.DepartmentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/facilities/{facility_id}/positions": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Position"
                ],
                "summary": "施設IDに紐づく役職を取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Facility ID",
                        "name": "facility_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_position.PositionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Position"
                ],
                "summary": "施設に紐づく役職を作成する",
                "parameters": [
                    {
                        "description": "Create Position Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_position.CreatePositionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_position.PositionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/facilities/{facility_id}/schedules": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schedule"
                ],
                "summary": "予定を作成する",
                "parameters": [
                    {
                        "description": "予定作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation_schedule.CreateScheduleRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "施設ID",
                        "name": "facility_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_schedule.CreateScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/facilities/{facility_id}/schedules/recurring": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schedule"
                ],
                "summary": "繰り返し予定を作成する",
                "parameters": [
                    {
                        "description": "予定作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation_schedule.CreateRecurringScheduleRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "施設ID",
                        "name": "facility_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_schedule.CreateRecurringScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/facilities/{facility_id}/schedules/schedule_types": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ScheduleType"
                ],
                "summary": "予定種別一覧を取得する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation_schedule_schedule_type.ScheduleTypeResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/facilities/{facility_id}/teams": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "施設IDに紐づくチームを取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Facility ID",
                        "name": "facility_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation_facility_team.TeamResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "施設に紐づくチームを作成する",
                "parameters": [
                    {
                        "description": "Create Team Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_team.CreateTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_team.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/facilities/{facility_id}/users": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "施設IDに紐づくユーザーを取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Facility ID",
                        "name": "facility_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Position",
                        "name": "position",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Department",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Team",
                        "name": "team",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Area",
                        "name": "area",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort Field",
                        "name": "sort_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort Order (asc or desc)",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation_user.UserResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "ヘルスチェック用エンドポイント",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_health_handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/policies": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "ポリシー一覧を取得する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation_policy.PolicyResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "ポリシーを作成する",
                "parameters": [
                    {
                        "description": "Create Policy Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/presentation_policy.CreatePolicyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presentation_policy.CreatePolicyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/policies/{policy_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policy"
                ],
                "summary": "単一のポリシーを取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policy_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_policy.PolicyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/positions/{position_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Position"
                ],
                "summary": "単一の役職を取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Position ID",
                        "name": "position_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_position.PositionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/teams/{team_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Team"
                ],
                "summary": "単一のチーム取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_facility_team.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "単一のユーザーを取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presentation_user.UserDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/visit_infos/service_codes": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceCode"
                ],
                "summary": "サービスコード一覧を取得する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation_visit_info_service_code.ServiceCodeResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/visit_infos/visit_categories": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VisitCategory"
                ],
                "summary": "訪問カテゴリ一覧を取得する",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/presentation_visit_info_visit_category.VisitCategoryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api-buddy_presentation_common.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api-buddy_domain_common.Date": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "api-buddy_domain_policy.Policy": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api-buddy_domain_schedule_recurring_rule.FrequencyEnum": {
            "type": "string",
            "enum": [
                "monthly",
                "weekly"
            ],
            "x-enum-varnames": [
                "FrequencyMonthly",
                "FrequencyWeekly"
            ]
        },
        "api-buddy_domain_schedule_schedule_type.ScheduleTypeEnum": {
            "type": "string",
            "enum": [
                "通常",
                "訪問"
            ],
            "x-enum-varnames": [
                "Normal",
                "Visit"
            ]
        },
        "api-buddy_domain_visit_info_visit_category.VisitCategoryType": {
            "type": "string",
            "enum": [
                "夜勤",
                "緊急",
                "入院"
            ],
            "x-enum-varnames": [
                "NightShift",
                "Emergency",
                "Hospital"
            ]
        },
        "api-buddy_presentation_common.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "api-buddy_usecase_facility_position.PolicyDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "presentation_address.AddressDetailResponse": {
            "type": "object",
            "properties": {
                "addressLine1": {
                    "type": "string"
                },
                "addressLine2": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "prefecture": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string"
                }
            }
        },
        "presentation_address.CreateAddressResponse": {
            "type": "object",
            "properties": {
                "addressLine1": {
                    "type": "string"
                },
                "addressLine2": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "prefecture": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "zipCode": {
                    "type": "string"
                }
            }
        },
        "presentation_auth.SignInRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "presentation_auth.SignInResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "id_token": {
                    "type": "string"
                }
            }
        },
        "presentation_auth.SignUpRequest": {
            "type": "object",
            "required": [
                "area_id",
                "department_id",
                "facility_id",
                "password",
                "position_id",
                "team_id",
                "username"
            ],
            "properties": {
                "area_id": {
                    "type": "string"
                },
                "department_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "facility_id": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "position_id": {
                    "type": "string"
                },
                "team_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "presentation_auth.SignUpResponse": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "facility": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api-buddy_domain_policy.Policy"
                    }
                },
                "position": {
                    "type": "string"
                },
                "team": {
                    "type": "string"
                }
            }
        },
        "presentation_facility_area.AddressModel": {
            "type": "object",
            "properties": {
                "address_line1": {
                    "type": "string"
                },
                "address_line2": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "prefecture": {
                    "type": "string"
                }
            }
        },
        "presentation_facility_area.AreaResponse": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presentation_facility_area.AddressModel"
                    }
                },
                "facility_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "presentation_facility_area.CreateAreaRequest": {
            "type": "object",
            "required": [
                "address_ids",
                "facility_id",
                "name"
            ],
            "properties": {
                "address_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "facility_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "presentation_facility_department.DepartmentResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "facility_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "presentation_facility_position.CreatePositionRequest": {
            "type": "object",
            "required": [
                "name",
                "policy_ids"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "policy_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "presentation_facility_position.PositionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "facility_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api-buddy_usecase_facility_position.PolicyDto"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "presentation_facility_team.CreateTeamRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "presentation_facility_team.TeamResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "facility_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "presentation_health_handler.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "presentation_policy.CreatePolicyRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "presentation_policy.CreatePolicyResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "presentation_policy.PolicyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "presentation_schedule.CreateRecurringScheduleRequest": {
            "type": "object",
            "required": [
                "date",
                "end_time",
                "schedule_type_id",
                "staff_id",
                "start_time"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "format": "date"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "recurring_rule": {
                    "$ref": "#/definitions/presentation_schedule.RecurringRuleRequestModel"
                },
                "schedule_type_id": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "visit_info": {
                    "$ref": "#/definitions/presentation_schedule.VisitInfoRequestModel"
                }
            }
        },
        "presentation_schedule.CreateRecurringScheduleResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "$ref": "#/definitions/api-buddy_domain_common.Date"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "recurring_rule": {
                    "$ref": "#/definitions/presentation_schedule.RecurringRuleResponseModel"
                },
                "schedule_type_id": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "visit_info": {
                    "$ref": "#/definitions/presentation_schedule.VisitInfoResponseModel"
                }
            }
        },
        "presentation_schedule.CreateScheduleRequest": {
            "type": "object",
            "required": [
                "date",
                "end_time",
                "schedule_type_id",
                "staff_id",
                "start_time"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "format": "date"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "schedule_type_id": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "visit_info": {
                    "$ref": "#/definitions/presentation_schedule.VisitInfoRequestModel"
                }
            }
        },
        "presentation_schedule.CreateScheduleResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "$ref": "#/definitions/api-buddy_domain_common.Date"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "schedule_type_id": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "visit_info": {
                    "$ref": "#/definitions/presentation_schedule.VisitInfoResponseModel"
                }
            }
        },
        "presentation_schedule.RecurringRuleRequestModel": {
            "type": "object",
            "required": [
                "frequency",
                "start_date"
            ],
            "properties": {
                "day_of_month": {
                    "type": "integer"
                },
                "days_of_week": {
                    "type": "integer"
                },
                "end_date": {
                    "type": "string",
                    "format": "date"
                },
                "frequency": {
                    "$ref": "#/definitions/api-buddy_domain_schedule_recurring_rule.FrequencyEnum"
                },
                "start_date": {
                    "type": "string",
                    "format": "date"
                },
                "week_of_month": {
                    "type": "integer"
                }
            }
        },
        "presentation_schedule.RecurringRuleResponseModel": {
            "type": "object",
            "properties": {
                "day_of_month": {
                    "type": "integer"
                },
                "days_of_week": {
                    "type": "integer"
                },
                "end_date": {
                    "$ref": "#/definitions/api-buddy_domain_common.Date"
                },
                "frequency": {
                    "$ref": "#/definitions/api-buddy_domain_schedule_recurring_rule.FrequencyEnum"
                },
                "start_date": {
                    "$ref": "#/definitions/api-buddy_domain_common.Date"
                },
                "week_of_month": {
                    "type": "integer"
                }
            }
        },
        "presentation_schedule.RouteRequestModel": {
            "type": "object",
            "required": [
                "destination_id",
                "from_address_id"
            ],
            "properties": {
                "destination_id": {
                    "type": "string"
                },
                "from_address_id": {
                    "type": "string"
                },
                "travel_time": {
                    "type": "integer"
                }
            }
        },
        "presentation_schedule.RouteResponseModel": {
            "type": "object",
            "properties": {
                "address_id": {
                    "type": "string"
                },
                "destination_id": {
                    "type": "string"
                },
                "travel_time": {
                    "type": "integer"
                }
            }
        },
        "presentation_schedule.VisitCategoryResponseModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/api-buddy_domain_visit_info_visit_category.VisitCategoryType"
                }
            }
        },
        "presentation_schedule.VisitInfoRequestModel": {
            "type": "object",
            "required": [
                "assign_staff_id",
                "patient_id",
                "service_code_id"
            ],
            "properties": {
                "assign_staff_id": {
                    "type": "string"
                },
                "companion_id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                },
                "route": {
                    "$ref": "#/definitions/presentation_schedule.RouteRequestModel"
                },
                "service_code_id": {
                    "type": "string"
                },
                "visit_category_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "presentation_schedule.VisitInfoResponseModel": {
            "type": "object",
            "properties": {
                "assigned_staff_id": {
                    "type": "string"
                },
                "companion_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                },
                "route": {
                    "$ref": "#/definitions/presentation_schedule.RouteResponseModel"
                },
                "service_code_id": {
                    "type": "string"
                },
                "visit_categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presentation_schedule.VisitCategoryResponseModel"
                    }
                }
            }
        },
        "presentation_schedule_schedule_type.ScheduleTypeResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/api-buddy_domain_schedule_schedule_type.ScheduleTypeEnum"
                }
            }
        },
        "presentation_user.PolicyModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "presentation_user.UserDetailResponse": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "facility": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "policies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presentation_user.PolicyModel"
                    }
                },
                "position": {
                    "type": "string"
                },
                "team": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "presentation_user.UserResponse": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "string"
                },
                "department": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "team": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "presentation_visit_info_service_code.ServiceCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "service_time_range_end": {
                    "type": "integer"
                },
                "service_time_range_start": {
                    "type": "integer"
                }
            }
        },
        "presentation_visit_info_visit_category.VisitCategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/api-buddy_domain_visit_info_visit_category.VisitCategoryType"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Buddy-API",
	Description:      "BuddyのAPIサーバー",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
